### ISSUE TITLE
Holy Paladin is casting Sacred Shield endlessly

### ISSUE THREAD

**Issue by Alejolas** [darhanger/WotLK_Profiles_for_nHub#8]
Hello, 

I was just testing these rotations and profiles and I noticed the holy paladin casts sacred shield like crazy between tank and myself.

Any ideas?

**Comment by darhanger** [comment]
It will be fixed soon.

**Comment by darhanger** [comment]
Fix for now.
Download from → https://1drv.ms/u/s!AmkmmtTdGkhggp4hE6dxSHRpAb7CZw?e=WeeWwA
